version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto para clientes AMQP
      - "15672:15672" # Puerto para la interfaz de administración web
    environment:
      - RABBITMQ_DEFAULT_USER=user  # Usuario por defecto
      - RABBITMQ_DEFAULT_PASS=password  # Contraseña por defecto
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistencia de datos
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge